apps/courses/urls.py
#-*- encodeing:utf-8 -*-

from django.conf.urls import url,include

from .views import CourseListView,CourseDetailsView,CourseInfoView,CourseCommentView


urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="course_list"),
    url(r'^details/(?P<course_id>.*)/$', CourseDetailsView.as_view(), name="course_details"),
    url(r'^info/(?P<course_id>.*)/$', CourseInfoView.as_view(), name="course_info"),
    url(r'^comment/(?P<course_id>.*)/$', CourseCommentView.as_view(), name="course_comment"),
]

apps/operation/urls.py
#-*- encodeing:utf-8 -*-

from django.conf.urls import url,include

from .views import AddCommentView


urlpatterns = [
    url(r'^add_comment/$', AddCommentView.as_view(), name="operation_add_comment"),
]

apps/organization/urls.py
#-*- encodeing:utf-8 -*-

from django.conf.urls import url,include

from .views import orglistView, AddUserAskView,OrgHomeView,OrgCouresView,OrgDescView,OrgTeacherView,AddUserFavView,TeacherListView,TeacherDetailsView


urlpatterns = [
    url(r'^list/$', orglistView.as_view(), name="org_list"),
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    url(r'^coures/(?P<org_id>\d+)/$', OrgCouresView.as_view(), name="org_coures"),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),
    
    url(r'^teacher/$', TeacherListView.as_view(), name="teacher_list"),
    
    url(r'^teacher/(?P<teacher_id>\d+)/$', TeacherDetailsView.as_view(), name="teacher_details"),
    #用户收藏
    url(r'^add_fav/$', AddUserFavView.as_view(), name="add_fav"),
]

apps/users/urls.py
#-*- encodeing:utf-8 -*-

from django.conf.urls import url,include

from .views import UserCenterInfoView,UserCenterMycourseView,UserCenterMessageView,UserCenterFavView,UploadImageView


urlpatterns = [
    url(r'^info/$', UserCenterInfoView.as_view(), name="usercenter_info"),
    url(r'^mycourse/$', UserCenterMycourseView.as_view(), name="usercenter_mycourse"),
    url(r'^fav/$', UserCenterFavView.as_view(), name="usercenter_fav"),
    url(r'^message/$', UserCenterMessageView.as_view(), name="usercenter_message"),
    url(r'^uploadimage/$', UploadImageView.as_view(), name="usercenter_uploadimage"),
]

mxonline/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve


from users.views import LoginView,RegisterView,ActiveUserView,ForgetPwdView,PwdResetView,setNewPwdView,LogoutView,IndexView
from courses.views import CourseListView
from mxonline.settings import MEDIA_ROOT #上传文件夹路径


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$',IndexView.as_view(), name ="index"),
    url('^login/$',LoginView.as_view(), name ="login"),
    url('^register/$',RegisterView.as_view(), name ="register"),
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name="active"),
    url(r'^forget_password/$', ForgetPwdView.as_view(), name="forgetpwd"),
    url(r'^reset/(?P<reset_code>.*)/$', PwdResetView.as_view(), name="reset"),
    url('^setnewpwd/$',setNewPwdView.as_view(), name ="setnewpwd"),
    url(r'^captcha/', include('captcha.urls')),#验证码

    #用户登出
    url('^logout/$', LogoutView.as_view(), name="logout"),

    #课程机构url配置
    url(r'^org/', include('organization.urls', namespace="org")),

    #公开课
    url(r'^course/', include('courses.urls', namespace="course")),

    #用户相关操作：评论
    url(r'^operation/', include('operation.urls', namespace="operation")),

    #公开课
    url(r'^usercenter/', include('users.urls', namespace="user")),

    #配置文件上传访问的函数
    url(r'^media/(?P<path>.*)$',  serve, {"document_root":MEDIA_ROOT}),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/course-comment.html
{% extends 'course-video.html' %}

{% block leftbox %}
<div class="mod-tab-menu">
        <ul class="course-menu clearfix">
            <li><a  class=" {% ifequal tag 'info' %}ui-tabs-active active{% endifequal %}" id="learnOn" href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
            <li><a  class=" {% ifequal tag 'comment' %}ui-tabs-active active{% endifequal %}" id="commentOn" class="" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
        </ul>
    </div>
<!--发布评论-->
<div id="js-pub-container" class="issques clearfix js-form">
    <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
        <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
    </div>
    <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
    <p class="global-errortip js-global-error"></p>
</div>
<div id="course_note">
    <ul class="mod-post" id="comment-list">
        {% for items in course.get_course_comment %}
            <li class="post-row">
                <div class="media">
                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ items.user.image }}' width='40' height='40' /></span>
                </div>
                <div class="bd">
                    <div class="tit">
                        <span target="_blank">{{ items.user.username }}</span>
                    </div>
                    <p class="cnt">{{ items.comments }}</p>
                    <div class="footer clearfix">
                        <span title="创建时间" class="l timeago">时间：{{ items.add_time }}</span>
                    </div>
                </div>
            </li>        
        {% endfor %}
    </ul>
</div>    
{% endblock leftbox %}


{% block commentjs %}
<script>
$('#js-pl-submit').on('click', function(){
    var comments = $("#js-pl-textarea").val()
    if(comments == ""){
        alert("评论不能为空")
        return
    }
    $.ajax({
        cache: false,
        type: "POST",
        url: '{% url 'operation:operation_add_comment' %}',
        data:{'course_id':{{ course.id }}, 'comments':comments},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                //window.location.reload();//刷新当前页面.
            }
        },
    });
}); 
</script>
{% endblock commentjs %}
    
    

templates/header.html
<section class="headerwrap ">
        <header>
            <div class=" header">
                <div class="top">
                    <div class="wp">
                        <div class="fl">
                            <p>服务电话：<b>33333333</b></p>
                        </div>
                        <!--登录后跳转-->
                        {% if request.user.is_authenticated %}
                            <div class="personal">
                                <dl class="user fr">
                                    <dd>{{ user.username }}<img class="down fr" src="/static/images/top_down.png" /></dd>
                                    <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                                </dl>
                                <div class="userdetail">
                                    <dl>
                                        <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                                        <dd>
                                            <h2>{{ request.user.nick_name }}</h2>
                                            <p>{{ request.user.username }}</p>
                                            <p>{{ request.user.id }}</p>
                                        </dd>
                                    </dl>
                                    <div class="btn">
                                        <a class="personcenter fl" href="{% url 'user:usercenter_info' %}">进入个人中心</a>
                                        <a class="fr" href="/logout/">退出</a>
                                    </div>
                                </div>
                            </div>  
                            {% else %}
                            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>                   
                        {% endif %}
                    </div>
                </div>
                <div class="middle">
                    <div class="wp">
                        <a href="/"><img class="fl" src="/static/images/logo.jpg" /></a>
                        <div class="searchbox fr">
                            <div class="selectContainer fl">
                                <span class="selectOption" id="jsSelectOption" data-value="course">
                                    公开课
                                </span>
                                <ul class="selectMenu" id="jsSelectMenu">
                                    <li data-value="course">公开课</li>
                                    <li data-value="org">课程机构</li>
                                    <li data-value="teacher">授课老师</li>
                                </ul>
                            </div>
                            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容" />
                            <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png" />
                        </div>
                    </div>
                </div>
                <nav>
                    <div class="nav">
                        <div class="wp">
                            <ul>
                                <li {% if request.path == '/' %}class="active" {% endif %}><a href="/">首页</a></li>
                                <li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
                                    <a href="{% url 'course:course_list' %}">
                                        公开课<img class="hot" src="/static/images/nav_hot.png">
                                    </a>
                                </li>
                                <li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
                                    <a href="{% url 'org:teacher_list' %}">授课教师</a>
                                </li>
                                <li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %}><a href="{% url 'org:org_list' %}">授课机构</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
    </section>

templates/index.html
{% extends 'base.html' %}
{% block title %} 首页{% endblock title %}
{% block content %}
<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    {% for items in all_banners  %}
                    <li>
                        <a href="{{ items.url }}">
                            <img width="1200" height="478" src="{{ MEDIA_URL }}{{ items.image }}" />
                        </a>
                    </li>                      
                    {% endfor %}
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
    </div>
</div>
<!--banner end-->
<!--feature start-->
<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="/static/images/feature1.png" />
                <p class="center">专业权威</p>
            </li>
            <li class="feature2">
                <img class="pic" src="/static/images/feature2.png" />
                <p class="center">课程最新</p>
            </li>
            <li class="feature3">
                <img class="pic" src="/static/images/feature3.png" />
                <p class="center">名师授课</p>
            </li>
            <li class="feature4">
                <img class="pic" src="/static/images/feature4.png" />
                <p class="center">数据真实</p>
            </li>
        </ul>
    </div>
</section>
<!--feature end-->
<!--module1 start-->
<section>
    <div class="module">
        <div class="wp">
            <h1>公开课程</h1>
            <div class="module1 eachmod">
                <div class="module1_1 left">
                    <img width="228" height="614" src="/static/images/module1_1.jpg" />
                    <p class="fisrt_word">名师授课<br />专业权威</p>
                    <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
                </div>
                <div class="right group_list">
                    <div class="module1_2 box">
                        <div class="imgslide2">
                            <ul class="imgs">
                                {% for items  in banner_courses %}
                                <li>
                                    <a href="{% url 'course:course_details' items.id %}">
                                        <img width="470" height="300" src="{{ MEDIA_URL }}{{ items.cover }}" />
                                    </a>
                                </li>                                    
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="unslider-arrow2 prev"></div>
                        <div class="unslider-arrow2 next"></div>
                    </div>
                    {% for items in courses  %}
                    <div class="module1_1 box">
                        <a href="{% url 'course:course_details' items.id %}">
                            <img width="233" height="190" src="{{ MEDIA_URL }}{{ items.cover }}" />
                        </a>
                        <div class="des">
                            <a href="course-detail.html">
                                <h2 title="django入门">{{ items.name }}</h2>
                            </a>
                            <span class="fl">难度：<i class="key">{{ items.get_degree_display }}</i></span>
                            <span class="fr">学习人数：{{ items.students }}</span>
                        </div>
                        <div class="bottom">
                            <span class="fl" title="{{ items.coures_org.name }}">{{ items.coures_org.name }}</span>
                            <span class="star fr">{{ items.fav_num }}</span>
                        </div>
                    </div>                      
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="module greybg">
        <div class="wp">
            <h1>课程机构</h1>
            <div class="module3 eachmod">
                <div class="module3_1 left">
                    <img width="228" height="463" src="/static/images/module3_1.jpg" />
                    <p class="fisrt_word">名校来袭<br />权威认证</p>
                    <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
                </div>
                <div class="right">
                    <ul>
                        {% for items in course_orgs  %}
                        <li class="">
                            <a href="{% url 'org:org_home' items.id %}">
                                <div class="company">
                                    <img width="184" height="100" src="{{ MEDIA_URL }}{{ items.image }}" />
                                    <div class="score">
                                        <div class="circle">
                                            <h2>{{ items.name }}</h2>
                                        </div>
                                    </div>
                                </div>
                                <p><span class="key" title="{{ items.name }}">{{ items.name }}</span></p>
                            </a>
                        </li>                          
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/teachers-list.html
{% extends "base.html" %}

{% block title %}
授课讲师
{% endblock title %}


{% block content %}
<!--crumbs start-->
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="index.html">首页</a>></li>
            <li>课程讲师</li>
        </ul>
    </div>
</section>
<section>
    <div class="wp butler_list_box list">
        <div class='left'>
            <div class="butler_list layout">
                <div class="head">
                    <ul class="fl tab_header">
                        <li  class=" {% ifequal sort '' %}active{% endifequal %}"><a href="?sort=">全部</a> </li>
                        <li  class=" {% ifequal sort 'hot' %}active{% endifequal %}"><a href="?sort=hot">人气 &#8595;</a></li>
                    </ul>
                    <div class="fr butler-num">共<span class="key">9</span>人&nbsp;&nbsp;&nbsp;</div>
                </div>
                {% for teacher in teachers.object_list  %}
                    <dl class="des">
                        <dt>
                            <a href="{% url 'org:teacher_details' teacher.id %}">
                                <div class="picpic">
                                    <img width="100" height="100" class="scrollLoading" src="{{ MEDIA_URL }}{{ teacher.image }}" />
                                </div>
                            </a>
                            <div class="btn">
                                <div class="fr btn2 bdsharebuttonbox" data-text="授课教师-奥巴马-慕学在线" data-desc="我在#慕课网#发现了教师“奥巴马”，对学习中的小伙伴很有帮助，一起来看看吧。"
                                    data-comment="奥巴马金牌讲师，从业年限：5年">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </div>
                            </div>
                        </dt>
                        <dd>
                            <a href="{% url 'org:teacher_details' teacher.id %}">
                                <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
                            </a>
                            <ul class="cont">
                                <li>工作年限：<span>{{ teacher.work_years }}年</span></li>
                                <li>工作职位：<span>{{ teacher.work_position }}</span></li>
                                <li>就职公司：<span>{{ teacher.work_company }}&nbsp;</span></li>
                                <li>教学特点：<span>{{ teacher.points }}</span></li>
                            </ul>
                        </dd>
                        <a class="buy buyservice" href="{% url 'org:teacher_details' teacher.id %}"><br />查看<br />详情</a>
                    </dl>                  
                {% endfor %}
            </div>
            <div class="pageturn">
                    <ul>
                        {% if teachers.has_previous %}
                            <li class="long"><a href="?{{ teachers.previous_page_number.querystring }}">上一页</a></li>
                        {% endif %}
                        {% for page in teachers.pages %}
                            {% if page %}
                                {% ifequal page teachers.number %}
                                <li class="active">{{ page }}</li>
                                {% else %}
                                    <li><a href="?{{page.querystring}}" class="page">{{page}}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none">...</li>
                            {% endif %}
                        {% endfor %}
                        {% if teachers.has_next %}
                        <li class="long"><a href="?{{ teachers.next_page_number.querystring }}">下一页</a></li>
                        {% endif %}   
                    </ul>               
                </div>
        </div>
        <div class="right layout">
            <div class="head">讲师排行榜</div>
            {% for teacher in tj_teacher %}
                <dl class="des">
                    <span class="num fl">{{ forloop.counter }}</span>
                    <a href="{% url 'org:teacher_details' teacher.id %}">
                        <dt>
                            <img width="50" height="50" class="scrollLoading" src="{{ MEDIA_URL }}{{ teacher.image }}" />
                        </dt>
                    </a>
                    <dd>
                        <a href="{% url 'org:teacher_details' teacher.id %}">
                            <h1 title="bobby">{{ teacher.name }}</h1>
                        </a>
                        <p>工作年限：<span>{{   teacher.work_years }}年</span></p>
                    </dd>
                </dl>              
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}